#--------------------------------------
# My GitHUb Actions
# Uvaysjon Kholboev
#--------------------------------------

name: My_GitHubActions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Print the list of files/directories in your github repository.
        run : ls -a
      - name: Print content of your log.txt file.
        run : cat log.txt

