#--------------------------------------
# My GitHUb Actions
# Uvaysjon Kholboev
#--------------------------------------

name: My_GitHubActions
env:
  DEPLOY_VER : "${{ github.sha }}"
  YEAR       : "2021"

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  first_job:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
      - name: Print the list of files/directories in your github repository.
        run : ls -a
      - name: Print content of your log.txt file.
        run : cat /Task1/log.txt
      - name: Print “Hello from “your DEPLOY_VER variable’s content” commit”
        run : echo "Hello from ${{env.DEPLOY_VER}} commit"
        
  second_job:
    runs-on: ubuntu-latest
    needs  : [first_job]
    
    env    :
      MONTH             : "June"
      DAY__OF_THE_MONTH : "15"
      FAVORITE_DAY_OF_WEEK: "${{secrets.SECRET_DAY}}"
    
    steps:
      - name: Print the system date and time
        run : date
      - name: Print your variable’s content
        run : |
          echo "Day   - ${{env.DAY__OF_THE_MONTH}}"
          echo "Month - ${{env.MONTH}}"
          echo "Year  - ${{env.YEAR}}"
          echo "My favorite day of week is - ${{secrets.SECRET_DAY}}"
  

